version: '3'

services:
    sc2004:
        build: .
        #restart: always
        ports:
            - "8080:80"
        volumes:
            - C:\\Temp\\Docker:C:\\Docker
        command: cmd.exe /c "dir /a C:\Docker"
