version: '3'

services:
    drone-server:
        container_name: drone-server-$GITHEAD
        image: drone/drone:1.9.1-linux-amd64
        restart: always
        hostname: drone-server-$GITHEAD
        environment:
            - DRONE_GITLAB_SERVER=https://gitlab.com
            - DRONE_GITLAB_CLIENT_ID={{DRONE_GITLAB_CLIENT_ID}}
            - DRONE_GITLAB_CLIENT_SECRET={{DRONE_GITLAB_CLIENT_SECRET}}
            - DRONE_RPC_SECRET={{DRONE_RPC_SECRET}}
            - DRONE_SERVER_HOST={{DRONE_SERVER_HOST}}
            - DRONE_SERVER_PROTO={{DRONE_SERVER_PROTO}}
            - DRONE_GITLAB_SERVER=https://gitlab.com
            - DRONE_GITLAB_SERVER=https://gitlab.com
            - DRONE_GITLAB_SERVER=https://gitlab.com
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/lib/drone:/data
