version: '3'

services:
    gitlab:
        #build: .
        container_name: gitlab-$GITHEAD
        image: gitlab/gitlab-ee:12.10.14-ee.0
        #restart: always
        hostname: 'c77-e5440-1'
        #environment:
        #GITLAB_OMNIBUS_CONFIG: |
            #external_url 'http://c77-e5440-1/gitlab'
            # Add any other gitlab.rb configuration here, each on its own line
            #external_url 'http://gitlab.example.com:8929'
            #gitlab_rails['gitlab_shell_ssh_port'] = 2224
        ports:
            - "80:80"
            - "443:443"
            - "10022:22"
        #- '8929:8929'
        #- '2224:22'
        volumes:
            - /data/gitlab/config:/etc/gitlab
            - /data/gitlab/logs:/var/log/gitlab
            - /data/gitlab/data:/var/opt/gitlab
