version: "2"

networks:
    gitea:
        external: false

volumes:
    gitea:
        driver: local

services:
    server:
        #build: .
        image: gitea/gitea:1.12.3
        container_name: gitea-$GITHEAD
        #environment:
        #    - USER_UID=1000
        #    - USER_GID=1000
        restart: always
        networks:
            - gitea
        volumes:
            - gitea:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "3000:3000"
            - "222:22"
