version: '3'

services:
    nginx:
        build: .
        #image: nginx:1.17.10-alpine
        #restart: always
        ports:
            - "8080:80"
        volumes:
              #- ./mysite.template:/etc/nginx/conf.d/mysite.template
              #- /data/nginx/html:/usr/share/nginx/html
              #- /data/nginx/conf/nginx.conf:/usr/local/nginx/conf/nginx.conf
              #- /data/nginx/conf/vhost:/usr/local/nginx/conf/vhost
            - /data/nginx/log:/var/log/nginx
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./html:/usr/share/nginx/html:ro
              #- /data/nginx/conf.d:/etc/nginx/conf.d
              #- /data/nginx/hosts:/etc/hosts
        environment:
            #- NGINX_HOST=foobar.com
            - NGINX_PORT=80
              #command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
        command: /bin/sh -c "exec nginx -g 'daemon off;'"
